Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using projeto_gamer.Infra;
using projeto_gamer.Models;

namespace projeto_gamer.Controllers
{
    [Route("[controller]")]
    public class PlayerController : Controller
    {
        private readonly ILogger<PlayerController> _logger;

        public PlayerController(ILogger<PlayerController> logger)
        {
            _logger = logger;
        }

        Context c = new Context();


        [Route("List")] //http://localhost/Player/List
        public IActionResult Index()
        {
           ViewBag.UserName = HttpContext.Session.GetString("UserName");
            ViewBag.Player = c.Player.ToList();
            ViewBag.Team = c.Team.ToList(); //variavel que armazena equipes e players do db

            //retorna a view de equipe (TELA)
            return View();
        }

        [Route("Register")]
        public IActionResult Register(IFormCollection form)
        {
            Player newPlayer = new Player();

            newPlayer.Name = form["Name"].ToString();

            newPlayer.Email = form["Email"].ToString();

            newPlayer.Password = form["Password"].ToString();

            newPlayer.Id = int.Parse((form["PlayerTeam"].ToString()));

            c.Player.Add(newPlayer);

            c.SaveChanges();

            return LocalRedirect("~/Player/List");
        }

        [Route("Delete/id")]
        public IActionResult Delete(int id)
        {

            Player foundPlayer = c.Player.First(t => t.PlayerId == id);

            c.Remove(foundPlayer);

            c.SaveChanges();

            return LocalRedirect("~/Player/List");
        }

        [Route("Edit/id")]
        public IActionResult Edit(int id)
        {
            ViewBag.UserName = HttpContext.Session.GetString("UserName");

            Player foundPlayer = c.Player.First(e => e.PlayerId == id);

            ViewBag.Player = foundPlayer;
            ViewBag.Team = c.Team.ToList();

            return View("Edit");

        }

        [Route("Update")]
        public IActionResult Update(IFormCollection form)
        {

            Player newPlayer = new Player();

            newPlayer.PlayerId = int.Parse(form["PlayerId"].ToString());

            newPlayer.Name = form["Name"].ToString();

            newPlayer.Email = form["Email"].ToString();

            newPlayer.Password = form["Password"].ToString();

            newPlayer.Id = int.Parse(form["PlayerTeam"].ToString());

            Player foundPlayer = c.Player.First(x => x.PlayerId == newPlayer.PlayerId);

            foundPlayer.Name = newPlayer.Name;
            foundPlayer.Email = newPlayer.Email;
            foundPlayer.Password = newPlayer.Password;
            foundPlayer.Id = newPlayer.Id;

            c.Player.Update(foundPlayer);

            c.SaveChanges();

            return LocalRedirect("~/Player/List");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using projeto_gamer.Infra;
using projeto_gamer.Models;

namespace projeto_gamer.Controllers
{
    [Route("[controller]")]
    public class TeamController : Controller
    {
        private readonly ILogger<TeamController> _logger;

        public TeamController(ILogger<TeamController> logger)
        {
            _logger = logger;
        }

        //instancia do contexto para acessar o banco de dados

        Context c = new Context();

        [Route("List")] //http://localhost/Team/List
        public IActionResult Index()
        {
            ViewBag.UserName = HttpContext.Session.GetString("UserName");
            ViewBag.Team = c.Team.ToList(); //variavel que armazena equipes do db

            //retorna a view de equipe (TELA)
            return View();
        }

        [Route("Register")]
        public IActionResult Register(IFormCollection form)
        {
            Team newTeam = new Team();

            newTeam.Name = form["Name"].ToString();
            // newTeam.Image = form["Image"].ToString();
            //string

            // newTeam.Image = form["Image"]

            if (form.Files.Count > 0)
            {
                var file = form.Files[0];

                var folder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/Teams");

                if (!Directory.Exists(folder))
                {
                    Directory.CreateDirectory(folder);
                }

                //gera o caminho completo at[e o caminho do arquivo(imagem - nome da extensao)
                var path = Path.Combine(folder, file.FileName);

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    file.CopyTo(stream);
                }

                newTeam.Image = file.FileName;
            }
            else
            {
                newTeam.Image = "padrao.png";
            }

            c.Team.Add(newTeam);

            c.SaveChanges();

            return LocalRedirect("~/Team/List");
        }


        [Route("Edit/id")]
        public IActionResult Edit(int id)
        {

            ViewBag.UserName = HttpContext.Session.GetString("UserName");

            Team foundTeam = c.Team.FirstOrDefault(e => e.Id == id)!;

            ViewBag.Team = foundTeam;

            return View("Edit");

        }

        [Route("Update")]
        public IActionResult Update(IFormCollection form)
        {

            Team newTeam = new Team();

            newTeam.Id = int.Parse(form["Id"].ToString());

            newTeam.Name = form["Name"].ToString();

            if (form.Files.Count > 0)
            {
                var file = form.Files[0];

                var folder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/Teams");

                if (!Directory.Exists(folder))
                {
                    Directory.CreateDirectory(folder);
                }

                //gera o caminho completo at[e o caminho do arquivo(imagem - nome da extensao)
                var path = Path.Combine(folder, file.FileName);

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    file.CopyTo(stream);
                }

                newTeam.Image = file.FileName;
            }
            else
            {
                newTeam.Image = "padrao.png";
            }

            Team foundTeam = c.Team.First(x => x.Id == newTeam.Id);

            foundTeam.Name = newTeam.Name;
            foundTeam.Image = newTeam.Image;

            c.Team.Update(foundTeam);

            c.SaveChanges();

            return LocalRedirect("~/Team/List");
        }

        [Route("Delete/id")]
        public IActionResult Delete(int id)
        {

            Team foundTeam = c.Team.First(t => t.Id == id);

            c.Remove(foundTeam);

            c.SaveChanges();

            return LocalRedirect("~/Team/List");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Shared/_Layout copy.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - projeto_gamer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/projeto_gamer.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css">
</head>
<body>

<header class="header">
        <div class="header-top">
            <div class="container-grid header-top-flex">
                <div>
                    <span class="phone-box">
                        <img src="~/assets/phone-icon.png" alt="phone icon" title="Ícone Telefone">
                        (11) 0900-1010
                    </span>

                    <span class="mail-box">
                        <img src="~/assets/envelope-icon.png" alt="envelope icon" title="Ícone Envelope">
                        contato@gamer.com.br
                    </span>
                </div>

                <span class="social-box">
                    <img src="~/assets/facebook.svg" alt="phone icon" title="Ícone Telefone">
                    <img src="~/assets/linkedin.svg" alt="phone icon" title="Ícone Telefone">
                    <img src="~/assets/instagram.svg" alt="phone icon" title="Ícone Telefone">
                </span>
            </div>
        </div>
        <div class="header-bottom">
            <div class="container-grid header-bottom">
                <label for="mostra-esconde-navmenu"><img src="~/assets/menu-hamburger.svg" alt="Menu Hamburger"
                        title="Ícone Menu">
                </label>


                <h1 asp-area="" asp-controller="Home" asp-action="Index">
                    <span class="title">Gamer</span>
                    <img src="~/assets/logotipo-gamer.svg" id="logotipo" alt="Logotipo Gamer" title="Gamer Logotipo">
                </h1>

                <input type="checkbox" id="mostra-esconde-navmenu">
                <div class="nav-bkg">
                    <nav>
                        @if (ViewBag.UserName != null){
                        <a asp-area="" asp-controller="Home" asp-action="Index">Início</a>
                        <a asp-area="" asp-controller="Player" asp-action="Index">Jogadores</a>
                        <a asp-area="" asp-controller="Team" asp-action="Index">Equipes</a>
                        <a href="#">Notícias</a>
                        <a asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                        }
                        else{
                        <a asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        }

                        <a class="phone-box">
                            <img src="~/assets/phone-icon.png" alt="phone icon" title="Ícone Telefone">
                            (11) 0900-1010
                        </a>
                        <a class="mail-box">
                            <img src="~/assets/envelope-icon.png" alt="envelope icon" title="Ícone Envelope">
                            contato@gamer.com.br
                        </a>

                        <!-- social icons -->
                        <span class="social-box">
                            <img src="~/assets/facebook.svg" alt="phone icon" title="Ícone Telefone">
                            <img src="~/assets/linkedin.svg" alt="phone icon" title="Ícone Telefone">
                            <img src="~/assets/instagram.svg" alt="phone icon" title="Ícone Telefone">
                        </span>
                    </nav>
                </div>
                <!-- Header Menu Ícones laterais -->
                <label for="mostra-esconde-icones">
                    <img src="~/assets/menu-points.png" alt="Menu Points">
                </label>

                <input type="checkbox" id="mostra-esconde-icones">
                <div class="icons-header-bkg">
                    <div class="icons-header">
                        <img src="~/assets/user-icon.svg" alt="user-login">
                        <img src="~/assets/market-icon.png" alt="market icon">
                        <img src="~/assets/search-icon.png" alt="search icon">
                    </div>
                </div>
            </div>
        </div>
    </header>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

<footer>
        <div class="container-grid footer-flex">
                        <i>Olá @ViewBag.UserName</i>

            <div class="card-ftitem-box">
                <a href="#" id="ftlogo-link">
                    <img src="./assets/logotipo-gamer.svg" id="ftlogo" alt="Home">
                </a>
                <p>Nosso sucesso na criação de soluções de negócios se deve em grande parte à nossa equipe talentosa e
                    altamente comprometida.</p>
                <div class="social-fticons">
                    <a href="#">
                        <img src="./assets/facebook-yellow.svg" alt="Icone Facebook">
                    </a>
                    <a href="#">
                        <img src="./assets/linkedin-yellow.svg" alt="Icone Linkedin">
                    </a>
                    <a href="#">
                        <img src="./assets/instagram-yellow.svg" alt="Icone instagram">
                    </a>
                </div>
            </div>


            <div class="card-ftitem-box">
                <div>
                    <h2>Links Úteis</h2>
                    <hr>
                </div>

                <ul class="menu-footer">
                    <li class="menu-ftitem"><a href="#">Início</a></li>
                    <li class="menu-ftitem"><a href="#">Jogadores</a></li>
                    <li class="menu-ftitem"><a href="#">Notícias</a></li>
                    <li class="menu-ftitem"><a href="#">Login</a></li>
                    <li class="menu-ftitem" id="link-equipe"><a href="#">Equipes</a></li>
                </ul>
            </div>

            <div class="card-ftitem-box">
                <div>
                    <h2>Contatos</h2>
                    <hr>
                </div>

                <div>
                    <p class="contact-title">Localização:</p>
                    <p class="contact-text">Rua Niterói, 180 - São Caetano do Sul - SP</p>

                    <p class="contact-title">Junte-se a nós:</p>
                    <p class="contact-text"><a href="mailto:contato">contato@gamer.com.br</a></p>

                    <p class="contact-title">Telefone:</p>
                    <p class="contact-text">(11) 0900-1010</p>
                </div>
            </div>

            <div class="card-ftitem-box">
                <div>
                    <h2>Newsletter</h2>
                    <hr>
                </div>

                <form action="" class="frm-news">
                    <div class="input-box">
                        <input type="text" class="frm-input" placeholder="Digite seu email:">
                    </div>
                    <button type="button" class="frm-button">Enviar</button>
                </form>
            </div>

        </div>

        <div id="copyright">
            &#169;Copyright2022-GamerJogosDigitais
        </div>

        <img src="./assets/Botao_voltar_ao_topo.svg" id="back-to-top" alt="Voltar ao Topo">
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
@model Player
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - projeto_gamer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/projeto_gamer.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css">
</head>
<body>

<header class="header">
        <div class="header-top">
            <div class="container-grid header-top-flex">
                <div>
                    <span class="phone-box">
                        <img src="~/assets/phone-icon.png" alt="phone icon" title="Ícone Telefone">
                        (11) 0900-1010
                    </span>

                    <span class="mail-box">
                        <img src="~/assets/envelope-icon.png" alt="envelope icon" title="Ícone Envelope">
                        contato@gamer.com.br
                    </span>
                </div>

                <span class="social-box">
                    <img src="~/assets/facebook.svg" alt="phone icon" title="Ícone Telefone">
                    <img src="~/assets/linkedin.svg" alt="phone icon" title="Ícone Telefone">
                    <img src="~/assets/instagram.svg" alt="phone icon" title="Ícone Telefone">
                </span>
            </div>
        </div>
        <div class="header-bottom">
            <div class="container-grid header-bottom">
                <label for="mostra-esconde-navmenu"><img src="~/assets/menu-hamburger.svg" alt="Menu Hamburger"
                        title="Ícone Menu">
                </label>

                    <a asp-controller="Home" asp-action="Index" >

                    <img src="~/assets/logotipo-gamer.svg" id="logotipo" alt="Logotipo Gamer" title="Gamer Logotipo">

                    </a>

                <input type="checkbox" id="mostra-esconde-navmenu">
                <div class="nav-bkg">
                    <nav>
                        <a asp-area="" asp-controller="Home" asp-action="Index">Início</a>
                        @if (ViewBag.UserName != null){
                        <a asp-area="" asp-controller="Player" asp-action="Index">Jogadores</a>
                        <a asp-area="" asp-controller="Team" asp-action="Index">Equipes</a>
                        
                        }
                        <a href="#noticias">Notícias</a>
                        

                        
                        <a class="phone-box">
                            <img src="~/assets/phone-icon.png" alt="phone icon" title="Ícone Telefone">
                            (11) 0900-1010
                        </a>
                        <a class="mail-box">
                            <img src="~/assets/envelope-icon.png" alt="envelope icon" title="Ícone Envelope">
                            contato@gamer.com.br
                        </a>

                        <!-- social icons -->
                        <span class="social-box">
                            
                            <img src="~/assets/facebook.svg" alt="phone icon" title="Ícone Telefone">
                            <img src="~/assets/linkedin.svg" alt="phone icon" title="Ícone Telefone">
                            <img src="~/assets/instagram.svg" alt="phone icon" title="Ícone Telefone">
                        </span>
                    </nav>
                </div>
                <!-- Header Menu Ícones laterais -->
                <label for="mostra-esconde-icones">
                    <img src="~/assets/menu-points.png" alt="Menu Points">
                </label>

                <input type="checkbox" id="mostra-esconde-icones">
                <div class="icons-header-bkg">
                    <div class="icons-header">
                        @if (ViewBag.UserName == null)
                        {
                        <a asp-area="" asp-controller="Login" asp-action="Index">
                        <img src="~/assets/user-icon.svg" alt="user-login">
                        </a>
                        }
                        else{
                        <a asp-area="" asp-controller="Login" asp-action="Logout">
                        <img src="~/assets/logout.svg" alt="user-login">
                        </a>
                        }
                        <img src="~/assets/market-icon.png" alt="market icon">
                        <img src="~/assets/search-icon.png" alt="search icon">
                    </div>
                </div>
            </div>
        </div>
    </header>
    
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div class="container-grid footer-flex">

            <div class="card-ftitem-box">
                <a href="#" id="ftlogo-link">
                    <img src="~/assets/logotipo-gamer.svg" id="ftlogo" alt="Home">
                </a>
                <p>Nosso sucesso na criação de soluções de negócios se deve em grande parte à nossa equipe talentosa e
                    altamente comprometida.</p>
                <div class="social-fticons">
                    <a href="#">
                        <img src="~/assets/facebook-yellow.svg" alt="Icone Facebook">
                    </a>
                    <a href="#">
                        <img src="~/assets/linkedin-yellow.svg" alt="Icone Linkedin">
                    </a>
                    <a href="#">
                        <img src="~/assets/instagram-yellow.svg" alt="Icone instagram">
                    </a>
                </div>
            </div>


            <div class="card-ftitem-box">
                <div>
                    <h2>Links Úteis</h2>
                    <hr>
                </div>

                <ul class="menu-footer">
                    <li class="menu-ftitem"><a asp-controller="Home" asp-action="Index">Início</a></li>
                    <li class="menu-ftitem"><a asp-controller="Player" asp-action="Index">Jogadores</a></li>
                    <li class="menu-ftitem"><a asp-controller="Home" asp-action="Index">Notícias</a></li>
                    @if (ViewBag.UserName == null)
                    {
                    <li class="menu-ftitem"><a asp-controller="Login" asp-action="Index">Login</a></li>
                    }
                    else{
                    <li class="menu-ftitem"><a asp-controller="Login" asp-action="Logout">Login</a></li>
                    }
                    <li class="menu-ftitem" id="link-equipe"><a asp-controller="Team" asp-action="Index">Equipes</a></li>
                </ul>
            </div>

            <div class="card-ftitem-box">
                <div>
                    <h2>Contatos</h2>
                    <hr>
                </div>

                <div>
                    <p class="contact-title">Localização:</p>
                    <p class="contact-text">Rua Niterói, 180 - São Caetano do Sul - SP</p>

                    <p class="contact-title">Junte-se a nós:</p>
                    <p class="contact-text"><a href="mailto:contato">contato@gamer.com.br</a></p>

                    <p class="contact-title">Telefone:</p>
                    <p class="contact-text">(11) 0900-1010</p>
                </div>
            </div>

            <div class="card-ftitem-box">
                <div>
                    <h2>Newsletter</h2>
                    <hr>
                </div>

                <form action="" class="frm-news">
                    <div class="input-box">
                        <input type="text" class="frm-input" placeholder="Digite seu email:">
                    </div>
                    <button type="button" class="frm-button">Enviar</button>
                </form>
            </div>

        </div>

        <div id="copyright">
            &#169;Copyright2022-GamerJogosDigitais
        </div>

        <img src="~/assets/Botao_voltar_ao_topo.svg" id="back-to-top" alt="Voltar ao Topo">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>